MEDICAL_RESPONSES = {
    "What is Diabetes": "Diabetes is a chronic condition that affects how your body turns food into energy.",
    "symptoms of flu": "Common symptoms of flu include fever, cough, sore throat, runny or stuffy nose, body aches, headache, chills, and fatigue.",
    "back pain": "Back pain can be caused by various factors including muscle strain, poor posture, or underlying medical conditions. It's important to consult a healthcare professional for a proper diagnosis.",
    "headache": "Headaches can be caused by stress, dehydration, or underlying medical conditions. Rest and hydration are often helpful. Over-the-counter pain relievers like ibuprofen or acetaminophen can also be used.",
    "Acne": "Use non-comedogenic skincare products, avoid picking lesions, and consider benzoyl peroxide or retinoids.",
    "Achalasia": "Eat small, frequent meals, avoid lying down after eating, and consider pneumatic dilation or surgery.",
    "Achlorhydria": "Take prescribed HCl supplements, eat smaller meals, and monitor for nutrient deficiencies.",
    "Acrophobia (Fear of Heights)": "Gradual exposure therapy, breathing exercises, and avoid unsafe high places.",
    "Actinic Keratosis": "Use sunscreen daily, apply prescribed fluorouracil cream, and monitor for skin changes.",
    "Acute Bronchitis": "Rest, stay hydrated, use honey for cough relief, and avoid irritants like smoke.",
    "Addison's Disease": "Take prescribed corticosteroids, monitor stress levels, and carry emergency hydrocortisone.",
    "Adenomyosis": "Use NSAIDs for pain, consider hormonal therapy, and discuss surgical options if severe.",
    "Adjustment Disorder": "Counseling, stress-management techniques, and maintain a supportive social network.",
    "Adrenal Fatigue (Controversial)": "Prioritize sleep, reduce stress, and consult an endocrinologist for testing.",
    "Agoraphobia": "Cognitive-behavioral therapy (CBT), gradual exposure, and carry anti-anxiety medication if prescribed.",
    "Albinism": "Use high-SPF sunscreen, wear UV-protective clothing, and get regular eye checkups.",
    "Alcohol Use Disorder": "Seek counseling/AA groups, avoid triggers, and consider medically supervised detox.",
    "Allergic Conjunctivitis": "Use antihistamine eye drops, avoid allergens, and apply cold compresses.",
    "Alopecia": "Topical minoxidil, corticosteroid injections, and consider wigs/scarves for hair loss.",
    "Altitude Sickness": "Descend immediately if severe, use acetazolamide for prevention, and stay hydrated.",
    "Alzheimer's Disease": "Cognitive exercises, maintain routines, and use prescribed cholinesterase inhibitors.",
    "Amblyopia (Lazy Eye)": "Eye patching therapy for children, vision exercises, and early ophthalmologist intervention.",
    "Amebiasis": "Take prescribed metronidazole, stay hydrated, and practice strict hand hygiene.",
    "Amenorrhea": "Address underlying causes (e.g., stress, PCOS), maintain healthy weight, and hormonal therapy if needed.",
    "Amyloidosis": "Follow specialist treatment (chemotherapy, organ-specific care), and monitor heart/kidney function.",
    "Anaphylaxis": "Use epinephrine auto-injector immediately, call emergency services, and avoid known allergens.",
    "Anemia": "Iron-rich diet (spinach, red meat), take supplements if deficient, and treat underlying causes.",
    "Angioedema": "Antihistamines, avoid triggers (foods, medications), and carry epinephrine for hereditary cases.",
    "Ankylosing Spondylitis": "Daily stretching, TNF inhibitors, and avoid prolonged sitting to reduce spinal stiffness.",
    "Anorexia Nervosa": "Nutritional rehabilitation, therapy, and gradual weight restoration under medical supervision.",
    "Anthrax": "Immediate antibiotics (ciprofloxacin/doxycycline), and report exposure to public health authorities.",
    "Antiphospholipid Syndrome": "Blood thinners (warfarin), monitor for clots, and avoid estrogen-containing contraceptives.",
    "Aortic Aneurysm": "Control blood pressure, quit smoking, and seek emergency surgery if rupture is suspected.",
    "Aphasia": "Speech therapy, use communication aids, and treat underlying causes (e.g., stroke).",
    "Apnea (Sleep)": "CPAP machine, weight loss, and avoid alcohol before bed.",
    "Appendicitis": "Seek emergency surgery, avoid laxatives, and don’t eat/drink until evaluated.",
    "Arteriosclerosis": "Low-cholesterol diet, exercise, and take statins as prescribed.",
    "Arthritis (Rheumatoid)": "DMARDs (methotrexate), gentle joint exercises, and use splints during flares.",
    "Asbestosis": "Avoid further exposure, pulmonary rehab, and monitor for lung cancer.",
    "Ascites": "Low-sodium diet, diuretics, and paracentesis for severe fluid buildup.",
    "Aspergillosis": "Antifungal medications, avoid moldy environments, and wear masks in dusty areas.",
    "Asthma": "Inhaled corticosteroids, identify triggers (pollen, smoke), and keep a rescue inhaler handy.",
    "Astigmatism": "Corrective lenses, LASIK surgery, and regular eye exams.",
    "Ataxia": "Physical therapy, assistive devices (canes/walkers), and treat underlying neurological causes.",
    "Atherosclerosis": "Statins, aspirin therapy, and Mediterranean diet to reduce plaque buildup.",
    "Athlete's Foot": "Antifungal creams, keep feet dry, and wear flip-flops in public showers.",
    "Atrial Fibrillation": "Blood thinners (warfarin), rate-control medications, and avoid excessive caffeine.",
    "Autism Spectrum Disorder": "Behavioral therapy, structured routines, and sensory-friendly environments.",
    "Autoimmune Hepatitis": "Immunosuppressants (prednisone), avoid alcohol, and monitor liver function.",
    "Avian Flu": "Antivirals (oseltamivir), isolate immediately, and report to health authorities.",
    "Bacillary Dysentery": "Ensure hydration, follow medical guidance for antibiotics, and practice proper hand hygiene.",
    "Babesiosis": "Seek medical care if symptoms appear; treatment typically involves antiparasitic medications and supportive care.",
    "Bacterial Meningitis": "Immediate medical attention is crucial; follow prescribed antibiotics and supportive care. Vaccination can be preventive.",
    "Bacterial Vaginosis": "Maintain proper hygiene, use prescribed antibiotics, and avoid practices that disrupt the natural flora.",
    "Balanitis": "Maintain good genital hygiene, use prescribed antifungal or antibacterial treatments, and consult a healthcare provider for recurring symptoms.",
    "Barrett's Esophagus": "Follow a gastroenterologist’s advice; lifestyle modifications and regular monitoring are key to managing symptoms.",
    "Behçet's Disease": "Management often includes anti-inflammatory medications and immunosuppressants; regular follow-ups with a specialist are important.",
    "Bell's Palsy": "Early treatment with corticosteroids and physical therapy can aid recovery; protect the eye if it doesn’t close fully.",
    "Benign Prostatic Hyperplasia (BPH)": "Lifestyle changes and medications may relieve symptoms; consult a urologist for personalized treatment.",
    "Benign Paroxysmal Positional Vertigo (BPPV)": "Often managed with canalith repositioning maneuvers; follow up with a specialist if symptoms persist.",
    "Beta Thalassemia": "Management may include regular blood transfusions and iron chelation therapy; consult a hematologist for guidance.",
    "Bicuspid Aortic Valve": "Regular cardiac monitoring is important; lifestyle modifications and consultation with a cardiologist can help manage complications.",
    "Bipolar Disorder": "Treatment involves mood stabilizers, therapy, and a strong support system; work closely with a mental health professional.",
    "Bladder Cancer": "Follow a urologist’s treatment plan which may include surgery, chemotherapy, or immunotherapy; regular monitoring is essential.",
    "Bladder Infection (Cystitis)": "Increase fluid intake, use prescribed antibiotics, and practice good urinary hygiene to reduce recurrence.",
    "Blepharitis": "Maintain eyelid hygiene with warm compresses and follow prescribed treatments like antibiotic or steroid drops.",
    "Botulism": "Seek immediate medical attention; treatment may include antitoxins and supportive care. Prevention through proper food handling is key.",
    "Brain Tumor": "Management depends on type and location; treatment may involve surgery, radiation, or chemotherapy. Consult a specialist for guidance.",
    "Bronchiectasis": "Management includes airway clearance techniques, antibiotics for infections, and regular follow-ups with a pulmonologist.",
    "Bronchitis": "Rest, stay hydrated, and avoid irritants; if bacterial, follow prescribed antibiotics. Consult a healthcare provider if symptoms worsen.",
    "Bruxism": "Consider using a dental guard, stress management techniques, and consult a dentist to prevent tooth damage.",
    "Budd-Chiari Syndrome": "Requires careful medical management, often including anticoagulation therapy and sometimes interventional procedures; regular follow-up is important.",
    "Burns": "Immediate cooling, proper wound care, and pain management are essential; severe burns require prompt medical attention.",
    "Basal Cell Carcinoma": "Early detection and treatment are key; options may include surgical removal or topical therapies. Regular skin checks are recommended.",
    "Binge Eating Disorder": "Management includes therapy, nutritional counseling, and support groups; consult a mental health professional for personalized treatment.",
    "Bacterial Pneumonia": "Use prescribed antibiotics and support with rest and hydration; seek immediate medical attention if symptoms worsen.",
    "Bartonella Infections": "Follow prescribed antibiotics; seek medical care for proper diagnosis and treatment based on the type of infection.",
    "Biliary Atresia": "Early diagnosis and intervention (including surgery or liver transplant) are crucial for managing this condition in infants.",
    "Biliary Cirrhosis": "Follow a prescribed treatment plan, including medications to manage symptoms, and consider liver transplantation if severe.",
    "Bipolar II Disorder": "Treatment with mood stabilizers, therapy, and regular mental health monitoring are essential for symptom management.",
    "Bleeding Disorders": "Treatment varies based on the disorder; clotting factor replacement therapy, medications, and lifestyle adjustments may be required.",
    "Brachial Plexus Injury": "Physical therapy, pain management, and surgical intervention may be required for recovery and rehabilitation.",
    "Brucellosis": "Treated with antibiotics; seek medical attention promptly for proper diagnosis and management.",
    "Bronchiolitis": "Supportive care like hydration, fever management, and nasal suctioning; consult a pediatrician for advice on managing symptoms.",
    "Brown Recluse Spider Bite": "Seek medical care if symptoms worsen; treatment may involve wound care, pain relief, and sometimes surgery for severe cases.",
    "Buerger's Disease": "Lifestyle changes (especially smoking cessation), medications for blood flow, and surgical interventions may be required.",
    "Burning Mouth Syndrome": "Consider oral hygiene changes, medications, and addressing underlying conditions like anxiety or hormonal imbalances.",
    "Bacterial Endocarditis": "Immediate intravenous antibiotics and possible surgery for valve repair or replacement are essential for treatment.",
    "Brachytherapy": "A type of radiation therapy used for localized cancers; treatment should be done under the guidance of a specialist.",
    "Bipolar Affective Disorder": "Mood stabilizers and therapy are key to managing episodes of mania and depression. Regular monitoring is required.",
    "Bowel Obstruction": "Seek immediate medical attention; treatment may include surgery, depending on the cause of the obstruction.",
    "Bilateral Ovarian Cysts": "May be monitored for growth or removed surgically if necessary, along with hormonal treatments to regulate menstrual cycles.",
    "Blount's Disease": "Treatment may include bracing or surgery depending on the severity of the condition, especially in children.",
    "Bilateral Hip Dysplasia": "Physical therapy and, in some cases, surgical intervention can help manage pain and improve mobility.",
    "Bovine Spongiform Encephalopathy (BSE)": "There is no cure, but the disease is rare and largely preventable by controlling cattle feed practices.",
    "Bacillus Calmette-Guérin (BCG) Infection": "Treatment may involve the use of antibiotics and supportive care; consult a healthcare provider for detailed advice.",
    "Back Pains": "Maintain good posture, exercise regularly, and use proper lifting techniques. Use pain relievers and consider physical therapy.",
    "Bacterial Vaginosis": "Take prescribed antibiotics and maintain good hygiene. Avoid douching and use condoms.",
    "Bedsoress": "Keep the skin clean and dry. Use pressure-relieving devices and reposition regularly. Seek medical attention for severe sores.",
    "Bell's Palsys": "Use prescribed medication and protect the affected eye. Consider physical therapy and massage.",
    "BPHs": "Follow prescribed treatment and manage symptoms with medication or surgery. Avoid caffeine and alcohol.",
    "Boilss": "Apply warm compresses and keep the area clean. Seek medical attention if the boil is large or painful.",
    "Bursitis": "Rest, ice, and elevate the affected joint. Use pain relievers and consider physical therapy.",
    "Biliary Colic": "Manage symptoms with dietary changes, pain relief, and consult a healthcare provider for further assessment.",
    "Biliary Obstruction": "Treatment involves identifying the cause, which may include surgery, medications, or endoscopic procedures.",
    "Bipolar Disorder Type I": "Mood stabilizers, antipsychotic medications, and psychotherapy are essential for managing manic and depressive episodes.",
    "Bladder Stones": "Treatment includes increased hydration, medications to dissolve stones, or surgical removal if necessary.",
    "Brachytherapy for Prostate Cancer": "A type of radiation therapy where radioactive seeds are implanted directly into the prostate; consult an oncologist for guidance.",
    "Bronchopulmonary Dysplasia": "Supportive care like oxygen therapy, respiratory treatments, and nutrition management are key in neonates with this condition.",
    "Budd-Chiari Syndrome": "Requires careful medical management, often including anticoagulation therapy and sometimes interventional procedures; regular follow-up is important.",
    "Burnout Syndrome": "Management includes stress reduction, therapy, time off from work, and support for mental well-being.",
    "Basal Ganglia Disorders": "Treatment may involve medications (e.g., levodopa for Parkinson's disease) and physical therapy to improve motor function.",
    "Bloating": "Lifestyle changes, dietary modifications (avoid gas-causing foods), and over-the-counter medications can help reduce bloating.",
    "Bipolar Depression": "Management with antidepressants and mood stabilizers; therapy and lifestyle support are also important.",
    "Babies with Jaundice": "Treatment may involve phototherapy or, in severe cases, a blood exchange procedure; regular monitoring is necessary.",
    "Brachial Plexus Avulsion": "Surgical intervention, physical therapy, and pain management are essential for recovery from nerve damage in the upper limb.",
    "Brown-Séquard Syndrome": "Management depends on the severity of neurological damage; treatments may include surgery, rehabilitation, and physical therapy.",
    "Bilateral Carpal Tunnel Syndrome": "Non-surgical treatments may include wrist splints, physical therapy, and corticosteroid injections; surgery is an option for severe cases.",
    "Bowel Cancer": "Treatment typically involves surgery, chemotherapy, and possibly radiation therapy depending on the stage of the cancer.",
    "Bowel Incontinence": "Management options include dietary changes, pelvic floor exercises, medications, and in some cases, surgery or medical devices.",
    "Basal Cell Nevus Syndrome": "Treatment may include regular skin checks, surgical removal of tumors, and monitoring for other associated conditions.",
    "Batten Disease": "A rare neurodegenerative disorder with no cure; management focuses on alleviating symptoms and supporting the patient’s quality of life.",
    "Bacterial Conjunctivitis": "Use prescribed antibiotics and practice good hygiene to prevent spread; avoid touching or rubbing the eyes.",
    "Blood Clots (Deep Vein Thrombosis)": "Treatment may include blood thinners (anticoagulants), compression stockings, and lifestyle changes to reduce recurrence.",
    "Brucellosis": "Treated with antibiotics; seek medical attention promptly for proper diagnosis and management.",
    "Batten Disease": "A rare neurodegenerative disorder with no cure; management focuses on alleviating symptoms and supporting the patient’s quality of life.",
    "Bacterial Conjunctivitis": "Use prescribed antibiotics and practice good hygiene to prevent spread; avoid touching or rubbing the eyes.",
    "Blood Clots (Deep Vein Thrombosis)": "Treatment may include blood thinners (anticoagulants), compression stockings, and lifestyle changes to reduce recurrence.",
    "Bicuspid Aortic Valve": "Regular cardiac monitoring is important; lifestyle modifications and consultation with a cardiologist can help manage complications.",
    "Blistering Diseases": "Treatment depends on the type of condition (e.g., pemphigus vulgaris, bullous pemphigoid); corticosteroids and immunosuppressive therapy may be used.",
    "Bacterial Superinfection": "Requires appropriate antibiotics based on culture and sensitivity testing; follow medical guidance closely.",
    "Bile Duct Cancer": "Treatment may involve surgery, chemotherapy, or radiation therapy, depending on the stage and location of the cancer.",
    "Biliary Atresia": "Early diagnosis and intervention (including surgery or liver transplant) are crucial for managing this condition in infants.",
    "Bipolar II Disorder": "Treatment with mood stabilizers, therapy, and regular mental health monitoring are essential for symptom management.",
    "Brittle Bone Disease (Osteogenesis Imperfecta)": "Treatment focuses on fracture prevention, pain management, and physical therapy to improve mobility and strength.",
    "Bowel Obstruction": "Seek immediate medical attention; treatment may include surgery, depending on the cause of the obstruction.",
    "Bacterial Endocarditis": "Immediate intravenous antibiotics and possible surgery for valve repair or replacement are essential for treatment.",
    "Blount's Disease": "Treatment may include bracing or surgery depending on the severity of the condition, especially in children.",
    "Bursitis": "Rest, ice, and anti-inflammatory medications are effective in managing inflammation in the affected bursa. Physical therapy may also be helpful.",
    "Bacterial Pneumonia": "Use prescribed antibiotics and support with rest and hydration; seek immediate medical attention if symptoms worsen.",
    "Brittle Diabetes": "Frequent blood glucose monitoring, adjustments to insulin therapy, and close follow-up with an endocrinologist are crucial.",
    "Biliary Obstruction": "Treatment may involve endoscopic or surgical procedures to clear the obstruction, along with medications to manage symptoms.",
    "Bladder Exstrophy": "Surgical intervention shortly after birth, followed by ongoing care, including regular checkups, is necessary to manage this congenital defect.",
    "Bleeding Ulcer": "Treatment involves proton pump inhibitors to reduce stomach acid and antibiotics for H. pylori infection, along with possible endoscopy to control bleeding.",
    "Bile Reflux": "Management includes medications to reduce acid production and lifestyle changes such as avoiding large meals and lying down after eating.",
    "Bartonella Infections": "Follow prescribed antibiotics; seek medical care for proper diagnosis and treatment based on the type of infection.",
    "Batten Disease": "A rare neurodegenerative disorder with no cure; management focuses on alleviating symptoms and supporting the patient’s quality of life.",
    "Bladder Cancer": "Follow a urologist’s treatment plan, which may include surgery, chemotherapy, or immunotherapy; regular monitoring is essential.",
    "Biliary Dyskinesia": "Treatment involves medications to stimulate bile flow, or in some cases, removal of the gallbladder if necessary.",
    "Cancer": "Treatment varies by type and stage; options include surgery, chemotherapy, radiation therapy, and immunotherapy. Early detection is key to better outcomes.",
    "Canker Sores": "Rinse with salt water, apply topical corticosteroid ointments, and avoid acidic or spicy foods to reduce irritation.",
    "Carpal Tunnel Syndrome": "Wrist splints, anti-inflammatory medications, physical therapy, and, in severe cases, surgery may be necessary.",
    "Celiac Disease": "Adhere to a strict gluten-free diet, ensure nutritional supplementation, and consult a gastroenterologist regularly.",
    "Chronic Fatigue Syndrome": "Energy conservation strategies, cognitive-behavioral therapy, and addressing underlying conditions may help manage symptoms.",
    "Chronic Kidney Disease": "Control underlying conditions like diabetes or hypertension, and follow dietary restrictions; dialysis or kidney transplant may be necessary for advanced stages.",
    "Chronic Pain": "Address underlying causes, use pain management strategies like medication, physical therapy, and relaxation techniques.",
    "Chronic Sinusitis": "Nasal irrigation, decongestants, antihistamines, and in some cases, surgery to improve drainage may provide relief.",
    "Cirrhosis": "Avoid alcohol, maintain a healthy diet, take prescribed medications, and consider liver transplant if liver failure occurs.",
    "Cleft Lip and Palate": "Surgical intervention early in life can improve function and appearance. Speech therapy may be necessary.",
    "Cluster Headaches": "Use abortive medications during an attack, such as triptans or oxygen therapy; preventive treatment may include medications like verapamil.",
    "Cochlear Implants": "Surgical placement of implants and rehabilitation through speech therapy help individuals with severe hearing loss regain hearing abilities.",
    "Common Cold": "Rest, stay hydrated, and use over-the-counter medications to relieve symptoms like congestion, runny nose, and sore throat.",
    "Conjunctivitis (Pink Eye)": "Use antibiotic eye drops for bacterial infections, antihistamine drops for allergic conjunctivitis, and avoid touching or rubbing the eyes.",
    "Concussion": "Rest, avoid activities that could cause further head injury, and consult a doctor if symptoms persist or worsen.",
    "Coronary Artery Disease": "Lifestyle changes (exercise, diet), medications, and sometimes surgical interventions (e.g., angioplasty or bypass surgery) are used to manage this condition.",
    "Cough": "Use cough suppressants, expectorants, stay hydrated, and avoid irritants. If symptoms persist, consult a doctor for a proper diagnosis.",
    "Crush Syndrome": "Immediate medical attention is crucial. Treatment includes fluid resuscitation, management of muscle damage, and addressing kidney function.",
    "Cushing's Syndrome": "Treatment may involve surgery to remove tumors, medication to control hormone levels, and lifestyle adjustments for managing symptoms.",
    "Cystic Fibrosis": "Regular chest physiotherapy, enzyme replacement, and antibiotics to treat lung infections are part of long-term management.",
    "Cervical Spondylosis": "Physical therapy, neck braces, pain relievers, and surgery in severe cases can help manage symptoms of degenerative neck disc disease.",
    "Cervical Cancer": "Treatment options include surgery, radiation, and chemotherapy, depending on the stage of cancer. Regular screening is essential for early detection.",
    "Cystitis": "Treatment involves antibiotics, increased fluid intake, and pain relievers. Urinary alkalinization may help relieve symptoms.",
    "Chronic Back Pain": "Physical therapy, pain medications, stretching exercises, and postural corrections are commonly recommended for managing chronic back pain.",
    "Chronic Shoulder Pain": "Physical therapy, anti-inflammatory medications, and corticosteroid injections may provide relief. Surgery may be necessary for severe cases, such as rotator cuff tears.",
    "Chronic Ear Pain": "Treatment depends on the cause; options include antibiotics for infections, warm compresses, and anti-inflammatory medications for relief.",
    "Costochondritis": "Nonsteroidal anti-inflammatory drugs (NSAIDs), rest, and applying heat or cold packs can relieve pain caused by inflammation of the cartilage in the rib cage.",
    "Cervicogenic Headache": "Physical therapy, pain medications, neck exercises, and posture correction can help alleviate headaches originating from neck problems.",
    "Chronic Migraines": "Use preventive medications (e.g., beta-blockers, antidepressants) and abortive medications (e.g., triptans) for relief during an attack. Lifestyle modifications can help reduce frequency.",
    "Cellulitis": "Treatment typically includes oral or intravenous antibiotics to address bacterial infection. Keep the affected area elevated and dry.",
    "Chlamydia": "Antibiotics (usually azithromycin or doxycycline) are prescribed to treat this sexually transmitted infection; notify partners to prevent reinfection.",
    "Chickenpox": "Calamine lotion, antihistamines, and fever reducers (acetaminophen) can help relieve itching and fever. Vaccination can prevent future outbreaks.",
    "Chronic Obstructive Pulmonary Disease (COPD)": "Quit smoking, use inhalers as prescribed, and avoid respiratory irritants. Pulmonary rehabilitation and oxygen therapy may help manage symptoms.",
    "Cystocele": "Pelvic floor exercises (Kegels), weight management, and in some cases, surgery to repair the prolapsed bladder may be necessary.",
    "Chondromalacia Patella": "Physical therapy, strengthening exercises, rest, and using a knee brace can help alleviate pain caused by cartilage damage behind the knee cap.",
    "Carcinoma of the Liver": "Treatment options include surgery, chemotherapy, radiation, and liver transplantation, depending on the extent of cancer. Early detection improves prognosis.",
    "Celiac Disease": "Strict adherence to a gluten-free diet and monitoring for deficiencies is essential in managing this autoimmune disorder.",
    "Cerebral Palsy": "Management includes physical therapy, occupational therapy, medications for spasticity, and surgical interventions for certain cases.",
    "Cervical Radiculopathy": "Physical therapy, pain medications, and in severe cases, surgery can help manage symptoms caused by nerve compression in the cervical spine.",
    "Chronic Fatigue Syndrome": "Energy conservation strategies, cognitive-behavioral therapy, and addressing underlying conditions may help manage symptoms.",
    "COVID-19s": "Isolate yourself, rest, and stay hydrated. Follow public health guidelines and seek medical attention if symptoms worsen.",
    "Cystitiss": "Take prescribed antibiotics and drink plenty of fluids. Avoid caffeine and alcohol.",
    "Chronic Pelvic Pain": "Physical therapy, pain management techniques (e.g., NSAIDs, nerve blocks), and addressing any underlying gynecological issues can help alleviate pain.",
    "Cervical Stenosis": "Treatment may include physical therapy, pain medications, and in some cases, surgery (e.g., laminectomy) to relieve pressure on the spinal cord.",
    "Chronic Fatigue Syndrome (CFS)": "A comprehensive treatment approach that includes pacing, cognitive-behavioral therapy (CBT), graded exercise therapy, and addressing any underlying conditions.",
    "Cystic Acne": "Topical treatments like benzoyl peroxide, oral antibiotics, or retinoids, and avoiding squeezing or picking the cysts to prevent further infection and scarring.",
    "Cystic Ovarian Disease": "Treatment can include hormonal therapy (birth control pills) or surgery in severe cases; pain relief may include NSAIDs or other medications.",
    "Chronic Nausea": "Medications (e.g., antiemetics), hydration, and identifying triggers like certain foods or stress can help manage symptoms.",
    "Chronic Tension Headaches": "Relieving muscle tension with relaxation exercises, yoga, stress management, and using NSAIDs or prescribed medications can help control headache frequency.",
    "Cranial Nerve Disorders": "Management depends on the specific nerve affected; treatments may include physical therapy, medication, or surgery for certain conditions like trigeminal neuralgia.",
    "Cervical Dysplasia": "Follow-up screenings, including Pap smears or colposcopy, to monitor and manage abnormal cell changes. In some cases, procedures like cryotherapy or laser treatment may be required.",
    "Cushing's Disease": "Treatment may include surgery to remove a tumor, radiation therapy, or medications that block excess cortisol production.",
    "Cold Sores (Herpes Simplex Virus)": "Antiviral medications, such as acyclovir, along with topical creams, can reduce the duration and severity of cold sores. Keep the area clean and avoid triggering stress.",
    "Chronic Ear Infections": "Long-term treatment may include antibiotics, ear drops, and possibly surgery to drain the infection or insert a tube to prevent fluid buildup.",
    "Celiac Disease": "Strict adherence to a gluten-free diet is the only current treatment. Regular follow-up for nutrient deficiencies is also essential.",
    "Cystic Fibrosis": "Ongoing respiratory therapy, enzyme replacement for digestion, and managing infections with antibiotics are essential for improving quality of life.",
    "Chronic Rhinitis": "Antihistamines, nasal corticosteroids, and saline nasal irrigation can help reduce inflammation and symptoms of chronic nasal congestion and irritation.",
    "Chronic Sinusitis": "Chronic sinus infections may be treated with long-term antibiotics, nasal steroids, saline rinses, and possibly surgery to improve sinus drainage.",
    "Chronic Diarrhea": "Address underlying conditions, use anti-diarrheal medications, stay hydrated, and follow dietary adjustments (low FODMAP diet) as needed.",
    "Celiac Disease": "Strict gluten-free diet to prevent intestinal damage, and ensure proper nutritional intake with possible vitamin and mineral supplementation.",
    "Cavernous Sinus Thrombosis": "Immediate treatment with antibiotics and sometimes surgery to remove infected tissue is critical for managing this life-threatening condition.",
    "Chronic Laryngitis": "Rest your voice, hydrate frequently, and use prescribed medications like corticosteroid inhalers if inflammation is severe. Avoid irritants such as smoke and alcohol.",
    "Chronic Bronchitis": "Smoking cessation, regular pulmonary rehabilitation, inhalers for bronchodilation, and anti-inflammatory medications can help manage symptoms and prevent flare-ups.",
    "Chronic Obstructive Pulmonary Disease (COPD)": "Quitting smoking, using inhalers (bronchodilators), oxygen therapy, and regular pulmonary rehabilitation to improve lung function.",
    "Chronic Tendonitis": "Rest the affected area, apply ice, use NSAIDs for pain relief, and engage in physical therapy to improve flexibility and strengthen muscles around the tendon.",
    "Chronic Shoulder Pain": "Strengthening exercises, physical therapy, anti-inflammatory medications, and corticosteroid injections can help manage persistent shoulder pain.",
    "Carpal Tunnel Syndrome": "Wrist splints, physical therapy, anti-inflammatory medications, and in some cases, surgery may be necessary to relieve compression of the median nerve.",
    "Chronic Abdominal Pain": "Identify and address underlying causes such as IBS, inflammatory bowel disease (IBD), or gastric ulcers. Pain relief can be achieved through medications, dietary changes, and stress management techniques.",
    "Cervical Spondylosis": "Physical therapy, anti-inflammatory drugs, corticosteroid injections, and sometimes surgical intervention (e.g., discectomy) may be necessary for nerve compression.",
    "Chronic Pain Syndrome": "Multidisciplinary approach with pain management specialists, physical therapy, psychotherapy (e.g., cognitive-behavioral therapy), and medications for pain relief.",
    "Celiac Disease": "Adherence to a gluten-free diet, along with regular health check-ups, is crucial in managing symptoms and preventing complications from this autoimmune disorder.",
    "Cleft Lip and Palate": "Surgical repair, speech therapy, and dental care are key for improving function and appearance. Early intervention is essential.",
    "Chronic Fatigue Syndrome (CFS)": "Balance activity and rest, engage in graded exercise therapy, and seek counseling to manage stress. Medication may help with symptoms.",
    "Chronic Sinusitis": "Use nasal saline rinses, decongestants, nasal corticosteroids, and antibiotics for infections. In severe cases, surgery may be required.",
    "Cranial Neuralgia": "Pain relief may involve nerve blocks, physical therapy, and medications like anticonvulsants or antidepressants.",
    "Chronic Rhinitis": "Use antihistamines, nasal sprays, and avoid allergens. Saline rinses and decongestants can also help alleviate symptoms.",
    "Chronic Insomnia": "Sleep hygiene, cognitive-behavioral therapy (CBT), and avoiding stimulants before bed can help manage symptoms. Medications may be prescribed for short-term use.",
    "Cervical Radiculopathy": "Physical therapy, pain relief (NSAIDs), and in severe cases, surgery to relieve nerve compression can help manage symptoms.",
    "Cystic Acne": "Topical treatments (benzoyl peroxide), antibiotics, and oral medications like retinoids or contraceptives may help manage acne.",
    "Carpal Tunnel Syndrome": "Wrist splints, physical therapy, and corticosteroid injections can help reduce symptoms. Surgery may be necessary for severe cases.",
    "Chronic Laryngitis": "Rest your voice, hydrate, and avoid irritants like smoke. Medications such as corticosteroids may help reduce inflammation.",
    "Celiac Disease": "Strict gluten-free diet, nutritional supplementation, and regular follow-up care are essential to managing symptoms.",
    "Chronic Bronchitis": "Avoid smoking, use bronchodilators and corticosteroids to manage symptoms, and get vaccinated against respiratory infections.",
    "Chronic Back Pain": "Physical therapy, posture correction, and pain medications (NSAIDs) can help relieve chronic back pain. In severe cases, surgery may be needed.",
    "Cushion's Syndrome": "Medications to reduce cortisol levels, surgery to remove tumors, and stress management are essential to managing this disorder.",
    "Chronic Heel Pain": "Rest, ice, stretching exercises, proper footwear, and orthotics can relieve pain caused by plantar fasciitis or heel spurs.",
    "Chronic Pelvic Pain": "Physical therapy, medication, and treating underlying gynecological or gastrointestinal conditions can help manage chronic pelvic pain.",
    "Chronic Stomach Pain": "Identify food triggers, use antacid medications, and manage stress. If caused by an underlying condition like ulcers or IBS, follow a treatment plan for that condition.",
    "Cavernous Sinus Thrombosis": "Immediate treatment with antibiotics and sometimes surgery is critical for managing this life-threatening infection.",
    "Cervical Spondylosis": "Physical therapy, anti-inflammatory drugs, and sometimes surgery can help manage symptoms of cervical spine degeneration.",
    "Chronic Diarrhea": "Treat underlying conditions (e.g., IBS, IBD), use anti-diarrheal medications, and ensure proper hydration.",
    "Chronic Migraine": "Preventive medications, avoiding triggers, and lifestyle adjustments (e.g., regular sleep patterns) are key. Triptans can help during acute attacks.",
    "Chronic Nausea": "Medications like antiemetics, ginger supplements, and stress management techniques can help alleviate nausea.",
    "Chronic Shoulder Pain": "Strengthening exercises, physical therapy, anti-inflammatory medications, and in some cases, surgery can relieve shoulder pain.",
    "Chronic Tension Headaches": "Stress management techniques like yoga, physical therapy for neck muscles, and medication can reduce the frequency and intensity of tension headaches.",
    "Chronic Foot Pain": "Supportive footwear, orthotics, stretching exercises, and pain medications can help manage chronic foot pain caused by conditions like plantar fasciitis.",
    "Chronic Hip Pain": "Physical therapy, pain relievers (NSAIDs), and in severe cases, joint replacement surgery can help manage chronic hip pain.",
    "Chronic Knee Pain": "Strengthening exercises, physical therapy, and medications can alleviate chronic knee pain. In some cases, surgery may be needed for joint replacement or repair.",
    "Chronic Wrist Pain": "Rest, physical therapy, wrist splints, and pain management techniques can help relieve chronic wrist pain caused by overuse or conditions like carpal tunnel syndrome.",
    "Chronic Tooth Pain": "Regular dental visits, proper oral hygiene, and treatments such as fillings, root canals, or extractions may be necessary to address the source of the pain.",
    "Cystocele": "Pelvic floor exercises, weight management, and surgery may be needed for more severe cases of bladder prolapse.",
    "Chronic Cough": "Identify and treat underlying conditions like asthma or GERD. Medications, lifestyle changes, and avoiding irritants can help manage a chronic cough.",
    "Chronic Sleep Apnea": "CPAP therapy, lifestyle changes (e.g., weight loss), and surgery may be needed to treat sleep apnea and improve sleep quality.",
    "Chronic Anxiety": "Cognitive-behavioral therapy (CBT), medications (e.g., SSRIs), and relaxation techniques (meditation, deep breathing) can help manage chronic anxiety.",
    "Chronic Depression": "Psychotherapy, antidepressants, and lifestyle changes (exercise, diet) can help alleviate symptoms of chronic depression.",
    "Chronic Pain Syndrome": "A multidisciplinary approach, including physical therapy, cognitive-behavioral therapy, and pain management techniques, is important for managing chronic pain syndrome.",
    "Cranial Nerve Disorder": "Treatment depends on the specific nerve involved and may include medications, physical therapy, and sometimes surgical intervention.",
    "Cervical Dysplasia": "Follow-up screenings, including Pap smears or colposcopy, and procedures like cryotherapy or laser treatment may be needed to manage abnormal cell growth.",
    "Chronic Fatigue Syndrome": "Gradual increases in activity, cognitive-behavioral therapy (CBT), and energy conservation techniques can help improve quality of life.",
    "Cerebral Palsy": "Physical therapy, occupational therapy, medications, and sometimes surgery may be used to manage motor function impairments associated with cerebral palsy.",
    "Chronic Constipation": "Increase fiber intake, stay hydrated, use laxatives or stool softeners as needed, and engage in regular physical activity to promote bowel movement.",
    "Chronic Hemorrhoids": "Dietary changes (increase fiber), sitz baths, topical treatments, and in severe cases, surgical intervention (hemorrhoidectomy) can help treat hemorrhoids.",
    "Chronic Ulcerative Colitis": "Medications such as aminosalicylates, corticosteroids, and immunosuppressive drugs can help manage symptoms of this inflammatory bowel disease.",
    "Chronic Liver Disease": "Avoid alcohol, take medications as prescribed, and follow dietary restrictions. In severe cases, a liver transplant may be necessary.",
    "Chronic Eczema": "Topical corticosteroids, moisturizers, and avoiding triggers (e.g., certain soaps or allergens) can help manage chronic eczema symptoms.",
    "Chronic Bronchitis": "Quit smoking, use inhalers as prescribed, and seek regular medical attention to manage chronic bronchitis symptoms and prevent flare-ups.",
    "Chronic Infections": "Antibiotics, antifungal medications, or antiviral treatments may be necessary to treat chronic infections, depending on the causative agent.",
    "Chronic Lower Back Pain": "Strengthening exercises, posture correction, NSAIDs, and physical therapy can help alleviate chronic lower back pain.",
    "Chronic Rhinosinusitis": "Nasal irrigation, decongestants, nasal corticosteroids, and in some cases, surgery, can help treat chronic rhinosinusitis.",
    "Chronic Pancreatitis": "Avoid alcohol, eat a low-fat diet, take pancreatic enzyme supplements, and in some cases, surgery or pancreatic enzyme therapy may be needed.",
    "Chronic Urticaria (Hives)": "Antihistamines, avoiding known triggers, and stress management can help prevent flare-ups and manage symptoms of chronic hives.",
    "Chronic Pain in the Lower Back": "Physical therapy, posture correction, heat and cold therapy, anti-inflammatory medications, and exercise can help alleviate chronic lower back pain.",
    "Dandruffs": "Use medicated shampoos and keep the scalp clean. Avoid scratching and use a gentle shampoo.",
    "Deep Vein Thrombosis": "Take prescribed medication and avoid prolonged inactivity. Elevate the affected limb and wear compression stockings.",
    "Dehydrations": "Drink plenty of fluids, especially water and electrolyte-rich beverages. Avoid caffeine and alcohol.",
    "Dengue Fevers": "Rest and stay hydrated. Seek medical attention for severe symptoms and avoid mosquito bites.",
    "Depressions": "Seek therapy or medication if needed. Practice self-care and engage in activities you enjoy.",
    "Diabetes": "Follow prescribed treatment and maintain a healthy lifestyle. Monitor blood sugar levels regularly.",
    "Diarrheas": "Stay hydrated and avoid dairy products. Use over-the-counter remedies and seek medical attention if severe.",
    "Dizziness": "Stay hydrated, avoid sudden movements, and sit or lie down if feeling dizzy. Seek medical attention if persistent.",
    "Dry Eyes": "Use artificial tears and avoid dry environments. Consider prescription eye drops if needed.",
    "Dry Skins": "Use gentle, fragrance-free moisturizers and avoid hot showers. Stay hydrated and use a humidifier.",
    "Dysmenorrheas": "Use pain relievers and apply heat to the lower abdomen. Exercise regularly and manage stress.",
    "Ear Infections": "Take prescribed antibiotics and use pain relievers. Apply a warm compress to the ear.",
    "Ear Pains": "Use over-the-counter pain relievers and apply a warm compress to the ear. Seek medical attention if severe or persistent.",
    "Eczemas": "Use gentle, fragrance-free moisturizers and avoid irritants. Consider prescribed creams and avoid scratching.",
    "Endometriosis": "Follow medical advice for treatment and manage symptoms with medication or surgery. Consider pain management techniques.",
    "Erectile Dysfunctions": "Seek medical advice for evaluation and treatment options. Maintain a healthy lifestyle and manage stress.",
    "Fifth Diseases": "Rest and stay hydrated. Avoid contact with pregnant women and practice good hygiene.",
    "Fibromyalgias": "Manage symptoms with medication, physical therapy, and lifestyle changes. Practice stress reduction techniques.",
    "Flatulences": "Avoid gas-producing foods, eat slowly, and exercise regularly. Use over-the-counter remedies if needed.",
    "Folliculitiss": "Keep the affected area clean and use antibacterial soap. Avoid shaving or irritating the skin.",
    "Food Poisonings": "Stay hydrated and avoid solid foods until symptoms subside. Seek medical attention if severe.",
    "Fungal Nail Infections": "Use prescribed antifungal medication and keep nails clean and dry. Consider laser treatment if severe.",
    "GERDs": "Avoid trigger foods, eat smaller meals, and stay upright after eating. Use antacids or prescribed medication.",
    "Gonorrheas": "Take prescribed antibiotics and avoid sexual contact until treated. Get tested for other STIs.",
    "Gouts": "Follow prescribed treatment and avoid trigger foods. Stay hydrated and maintain a healthy weight.",
    "Hair Loss": "Use prescribed treatments and manage stress. Consider support groups and avoid harsh hair treatments.",
    "Hand, Foot, and Mouth Diseases": "Rest and stay hydrated. Use pain relievers for discomfort and practice good hygiene.",
    "Headache": "Headaches can be caused by stress, dehydration, or underlying medical conditions. Rest and hydration are often helpful. Over-the-counter pain relievers like ibuprofen or acetaminophen can also be used.",
    "Heartburns": "Avoid trigger foods, eat smaller meals, and stay upright after eating. Use antacids or prescribed medication.",
    "Hemorrhoidss": "Use over-the-counter creams and sitz baths to relieve symptoms. Avoid straining during bowel movements.",
    "Hepatitis As": "Rest, stay hydrated, and avoid alcohol. Get vaccinated to prevent infection.",
    "Hepatitis Bs": "Follow prescribed treatment and avoid alcohol. Get vaccinated to prevent infection.",
    "Hepatitis Cs": "Follow prescribed treatment and avoid alcohol. Avoid sharing personal items.",
    "Hernias": "Seek medical advice for surgical repair. Avoid heavy lifting and straining.",
    "Herpes": "Use prescribed antiviral medication and avoid sexual contact during outbreaks. Practice safe sex.",
    "High Blood Pressures": "Follow prescribed treatment and maintain a healthy lifestyle. Monitor blood pressure regularly.",
    "HIV/AIDSs": "Follow prescribed antiretroviral therapy and maintain a healthy lifestyle. Practice safe sex.",
    "Hivess": "Use antihistamines and avoid triggers. Apply cool compresses to relieve itching.",
    "HPVs": "Follow medical advice for treatment and get vaccinated. Practice safe sex.",
    "Hyperthyroidisms": "Follow prescribed treatment and manage symptoms with medication or surgery. Avoid iodine-rich foods.",
    "Hypothyroidisms": "Follow prescribed treatment and monitor thyroid hormone levels regularly. Take medication as prescribed.",
    "Impetigos": "Use prescribed antibiotics and keep the affected area clean. Avoid touching or scratching the affected area.",
    "Infertilitys": "Seek medical advice for evaluation and treatment options. Maintain a healthy lifestyle and manage stress.",
    "Influenzas": "Rest, stay hydrated, and take antiviral medication if prescribed. Get vaccinated annually for prevention.",
    "Ingrown Toenails": "Soak the foot in warm water and gently lift the nail. Use over-the-counter remedies and seek medical attention if infected.",
    "Insomnias": "Practice good sleep hygiene, avoid caffeine and alcohol before bed, and exercise regularly. Consider therapy or medication if needed.",
    "Irritable Bowel Syndromes": "Manage symptoms with diet, stress reduction, and medication. Avoid trigger foods and eat smaller meals.",
    "Jock Itchs": "Keep the groin area clean and dry. Use antifungal powder or cream. Avoid tight-fitting clothing.",
    "Kidney Infections": "Take prescribed antibiotics and seek medical attention for complications. Drink plenty of fluids.",
    "Knee Pains": "Rest, ice, compression, and elevation (RICE). Use pain relievers and consider physical therapy.",
    "Lactose Intolerances": "Avoid dairy products or use lactase supplements. Choose lactose-free alternatives.",
    "Laryngitiss": "Rest your voice, stay hydrated, and avoid irritants. Use a humidifier and consider over-the-counter remedies.",
    "Lices": "Use over-the-counter treatments and keep the hair clean. Wash bedding and clothing in hot water.",
    "Low Back Pains": "Maintain good posture, exercise regularly, and use proper lifting techniques. Use pain relievers and consider physical therapy.",
    "Low Libidos": "Seek medical advice for evaluation and treatment options. Maintain a healthy lifestyle and manage stress.",
    "Lyme Diseases": "Take prescribed antibiotics and seek medical attention for complications. Avoid tick bites by using insect repellent.",
    "Malarias": "Seek medical treatment immediately. Use mosquito repellent to prevent bites and take prophylactic medication if traveling to endemic areas.",
    "Measless": "Isolate yourself, rest, and stay hydrated. Seek medical attention for complications and get vaccinated for prevention.",
    "Menopauses": "Manage symptoms with hormone therapy, lifestyle changes, and alternative remedies. Seek medical advice for treatment options.",
    "Menorrhagias": "Seek medical advice to determine the cause and follow appropriate treatment. Manage stress and maintain a healthy weight.",
    "Metrorrhagias": "Seek medical advice to determine the cause and follow appropriate treatment. Monitor menstrual cycles and report any changes.",
    "Migraines": "Use over-the-counter or prescribed pain relievers and avoid triggers. Practice relaxation techniques and maintain a regular sleep schedule.",
    "Mononucleosiss": "Rest, stay hydrated, and avoid contact sports. Seek medical attention for complications and avoid alcohol.",
    "Motion Sickness": "Take over-the-counter medication and avoid reading or looking at screens. Focus on the horizon and get fresh air.",
    "MRSA Infections": "Follow prescribed treatment and practice good hygiene to prevent spread. Keep wounds clean and covered.",
    "Mumps": "Isolate yourself, rest, and stay hydrated. Use pain relievers for discomfort and get vaccinated for prevention.",
    "Nasal Congestions": "Use over-the-counter decongestants and nasal sprays. Stay hydrated and use a humidifier.",
    "Nauseas": "Eat small, frequent meals and avoid strong odors. Use over-the-counter remedies and stay hydrated.",
    "Neck Pains": "Maintain good posture, exercise regularly, and use proper lifting techniques. Use pain relievers and consider physical therapy.",
    "Night Sweatss": "Keep the bedroom cool, wear lightweight clothing, and stay hydrated. Seek medical attention if persistent.",
    "Nosebleeds": "Pinch the nostrils together and lean forward. Apply ice to the bridge of the nose and avoid picking or blowing the nose.",
    "Obesities": "Follow a healthy diet, exercise regularly, and seek medical advice for treatment options. Consider support groups and lifestyle changes.",
    "Osteoarthritis": "Follow prescribed treatment and manage symptoms with medication, physical therapy, and lifestyle changes. Maintain a healthy weight.",
    "Osteoporosiss": "Follow prescribed treatment and maintain a healthy lifestyle. Take calcium and vitamin D supplements and exercise regularly.",
    "Ovarian Cystss": "Follow medical advice for treatment and monitor for changes. Consider pain management techniques and lifestyle changes.",
    "Overactive Bladders": "Follow prescribed treatment and manage symptoms with medication, bladder training, and lifestyle changes. Avoid caffeine and alcohol.",
    "Panic Disorders": "Seek therapy or medication if needed. Practice relaxation techniques and avoid triggers.",
    "Pelvic Inflammatory Diseases": "Take prescribed antibiotics and avoid sexual contact until treated. Get tested for other STIs and practice safe sex.",
    "Peyronie's Diseases": "Seek medical advice for evaluation and treatment options. Consider medication or surgery.",
    "PIDs": "Take prescribed antibiotics and avoid sexual contact until treated. Get tested for other STIs and practice safe sex.",
    "Pinkeyes": "Use prescribed eye drops and avoid touching the eyes. Practice good hygiene to prevent spread.",
    "Pneumonias": "Take prescribed antibiotics and rest. Seek medical attention for complications and get vaccinated for prevention.",
    "PCOSs": "Follow prescribed treatment and maintain a healthy lifestyle. Manage symptoms with medication, diet, and exercise.",
    "PMSs": "Manage symptoms with lifestyle changes and over-the-counter medication. Exercise regularly and practice stress reduction techniques.",
    "PMDDs": "Follow prescribed treatment and manage symptoms with medication and therapy. Seek support and practice self-care.",
    "Poison Ivys": "Wash the affected area with soap and water. Use over-the-counter creams and avoid scratching.",
    "Prostatitiss": "Take prescribed antibiotics and manage symptoms with medication and lifestyle changes. Avoid caffeine and alcohol.",
    "Psoriasis": "Moisturize regularly and avoid triggers. Consult a dermatologist for treatment and consider prescribed creams or light therapy.",
    "Pulled Muscles": "Rest, ice, compression, and elevation (RICE). Use pain relievers and consider physical therapy.",
    "Pulmonary Embolisms": "Seek immediate medical attention and follow prescribed treatment. Take anticoagulants and avoid prolonged inactivity.",
    "Rabiess": "Seek immediate medical attention for post-exposure prophylaxis. Vaccination is crucial for prevention and avoid contact with wild animals.",
    "Restless Legs Syndromes": "Manage symptoms with lifestyle changes, medication, and iron supplements. Avoid caffeine and alcohol.",
    "Ringworms": "Use antifungal cream and keep the area clean and dry. Avoid sharing personal items and practice good hygiene.",
    "Rosasceas": "Use prescribed medication and avoid triggers. Protect the skin from the sun and avoid harsh skincare products.",
    "Roseolas": "Rest and stay hydrated. Use fever-reducing medication if necessary and avoid contact with others.",
    "Rubellas": "Isolate yourself, rest, and stay hydrated. Avoid contact with pregnant women and get vaccinated for prevention.",
    "Scabiess": "Use prescribed treatments and keep the skin clean. Wash bedding and clothing in hot water and avoid close contact with others.",
    "Scarlet Fevers": "Take prescribed antibiotics and rest. Seek medical attention for complications and practice good hygiene.",
    "Sciaticas": "Maintain good posture, exercise regularly, and use proper lifting techniques. Use pain relievers and consider physical therapy.",
    "Shingles": "Take prescribed antiviral medication and use pain relievers. Get vaccinated to prevent shingles and avoid contact with pregnant women.",
    "Shoulder Pains": "Rest, ice, and elevate the affected shoulder. Use pain relievers and consider physical therapy.",
    "Sinus Infections": "Use over-the-counter decongestants and nasal sprays. Stay hydrated and use a humidifier.",
    "Sore Throats": "Gargle with warm salt water and use over-the-counter lozenges. Stay hydrated and avoid irritants.",
    "Sprainss": "Rest, ice, compression, and elevation (RICE). Use pain relievers and consider physical therapy.",
    "Strep Throats": "Take prescribed antibiotics and rest. Seek medical attention for complications and practice good hygiene.",
    "Stress": "Practice relaxation techniques, exercise regularly, and seek therapy or medication if needed. Manage time effectively and set realistic goals.",
    "Strokes": "Seek immediate medical attention and follow prescribed treatment. Manage risk factors and maintain a healthy lifestyle.",
    "Sunburns": "Apply cool compresses and use aloe vera gel. Stay hydrated and avoid further sun exposure.",
    "Swimmer's Ears": "Use prescribed ear drops and keep the ears dry. Avoid swimming in contaminated water and use earplugs.",
    "Syphiliss": "Take prescribed antibiotics and avoid sexual contact until treated. Get tested for other STIs and practice safe sex.",
    "Tendinitiss": "Rest, ice, compression, and elevation (RICE). Use pain relievers and consider physical therapy.",
    "Tetanuss": "Seek immediate medical attention for treatment with tetanus immunoglobulin and antibiotics. Vaccination is important for prevention and keep wounds clean.",
    "Tinnitus": "Avoid loud noises, manage stress, and seek medical advice for treatment options. Consider hearing aids or masking devices.",
    "Tonsillitiss": "Take prescribed antibiotics and rest. Seek medical attention for complications and gargle with warm salt water.",
    "Trichomoniasiss": "Take prescribed antibiotics and avoid sexual contact until treated. Get tested for other STIs and practice safe sex.",
    "Tuberculosiss": "Follow prescribed medication regimen and avoid spreading the infection. Practice good hygiene and get tested if exposed.",
    "Type 1 Diabetes": "Follow prescribed treatment and maintain a healthy lifestyle. Monitor blood sugar levels regularly and take insulin as prescribed.",
    "Type 2 Diabetes": "Follow prescribed treatment and maintain a healthy lifestyle. Monitor blood sugar levels regularly and take medication as prescribed.",
    "Ulcerative Colitiss": "Follow prescribed treatment and manage symptoms with medication, diet, and lifestyle changes. Avoid trigger foods and manage stress.",
    "UTIs": "Take prescribed antibiotics and drink plenty of fluids. Avoid caffeine and alcohol and practice good hygiene.",
    "Vaginal Yeast Infections": "Use antifungal treatments and keep the area clean and dry. Avoid douching and wear breathable clothing.",
    "Varicose Veins": "Elevate the legs, wear compression stockings, and exercise regularly. Seek medical advice for treatment options.",
    "Vertigos": "Stay hydrated, avoid sudden movements, and sit or lie down if feeling dizzy. Seek medical attention if persistent.",
    "Viral Fevers": "Rest, stay hydrated, and use fever-reducing medication if necessary. Avoid contact with others and seek medical attention if symptoms worsen.",
    "Vitiligos": "Use prescribed treatments and protect the skin from the sun. Consider camouflage makeup and support groups.",
    "Wartss": "Use over-the-counter or prescribed treatments to remove warts. Avoid touching or picking at warts and practice good hygiene.",
    "Whiplashes": "Rest, ice, and use pain relievers. Consider physical therapy and wear a neck brace if needed.",
    "Whooping Coughs": "Take prescribed antibiotics and rest. Seek medical attention for severe symptoms and get vaccinated for prevention.",
    "Wound Infections": "Keep the wound clean and covered. Use prescribed antibiotics and seek medical attention if symptoms worsen.",
    "Yeast Infections": "Use antifungal treatments and keep the area clean and dry. Avoid douching and wear breathable clothing.",
    "Zika Viruss": "Rest and stay hydrated. Avoid mosquito bites and seek medical advice if pregnant or planning to become pregnant.",
    "pimple skin": "For pimples, maintain a gentle skincare routine, avoid squeezing, and use over-the-counter treatments containing benzoyl peroxide or salicylic acid.",
    "chronic fatigue syndrome": "Persistent fatigue that doesn’t improve with rest. Manage stress, maintain a balanced diet, and follow a regular sleep schedule.",
    
    "fibromyalgia": "Widespread body pain, fatigue, and sleep disturbances. Exercise, stress reduction, and medications may help manage symptoms.",
    
    "gout": "A type of arthritis causing severe joint pain, usually in the big toe. Avoid high-purine foods and stay hydrated to prevent flare-ups.",
    
    "heel pain": "Commonly caused by plantar fasciitis or Achilles tendinitis. Stretch, wear supportive shoes, and use ice therapy.",
    
    "hip pain": "Can result from arthritis, bursitis, or injury. Apply ice or heat, do gentle stretches, and maintain a healthy weight.",
    
    "neck pain": "Poor posture, muscle strain, or cervical issues can cause neck pain. Use a firm pillow, stretch, and apply heat or cold packs.",
    
    "elbow pain": "Caused by overuse, arthritis, or injury. Rest, apply ice, and use a brace if necessary.",
    
    "hand pain": "Arthritis, carpal tunnel syndrome, or strain can cause hand pain. Do gentle stretches, use ergonomic tools, and apply ice if needed.",
    
    "wrist pain": "Often due to repetitive strain or carpal tunnel syndrome. Use wrist supports, take breaks from repetitive tasks, and do stretching exercises.",
    
    "finger pain": "Caused by arthritis, tendon issues, or injury. Apply warm compresses, use finger splints, and do gentle finger exercises.",
    
    "leg pain": "May result from muscle strain, poor circulation, or nerve issues. Elevate your legs, stretch, and avoid prolonged sitting.",
    
    "thigh pain": "Can be caused by muscle strain, nerve compression, or circulation issues. Apply heat, massage, and stretch to relieve discomfort.",
    
    "shin pain": "Shin splints are common in runners. Rest, ice, and proper footwear can prevent further issues.",
    
    "foot pain": "Causes include plantar fasciitis, bunions, or flat feet. Wear supportive shoes, do stretching exercises, and avoid prolonged standing.",
    
    "tingling in hands or feet": "May be due to nerve compression, diabetes, or circulation issues. Stay active, improve posture, and seek medical advice if persistent.",
    
    "dry skin": "Caused by weather, dehydration, or skin conditions. Moisturize regularly and avoid harsh soaps.",
    
    "eczema": "A chronic skin condition causing itchiness and irritation. Use hypoallergenic moisturizers and avoid triggers like allergens.",
    
    "psoriasis": "An autoimmune skin disorder leading to red, scaly patches. Use medicated creams, avoid stress, and follow dermatologist-recommended treatments.",
    
    "hives": "Red, itchy welts on the skin caused by allergies or stress. Take antihistamines and avoid known triggers.",
    
    "bloating": "Can result from indigestion, gas, or food intolerance. Avoid carbonated drinks, eat slowly, and try probiotics.",
    
    "acid reflux": "Burning sensation in the chest due to stomach acid backing up. Avoid spicy foods, eat smaller meals, and don't lie down right after eating.",
    
    "irritable bowel syndrome (IBS)": "Causes abdominal pain, bloating, and irregular bowel movements. Manage with diet, stress reduction, and fiber intake.",
    
    "food poisoning": "Symptoms include nausea, vomiting, diarrhea, and stomach cramps. Stay hydrated and eat bland foods while recovering.",
    
    "gas pain": "Gas buildup can cause bloating and discomfort. Drink warm water, move around, and try anti-gas medications.",
    
    "appendicitis": "Severe right lower abdominal pain, nausea, and fever. Seek emergency medical attention immediately.",
    
    "hernia": "A bulge in the abdomen due to internal organs pushing through muscles. Avoid heavy lifting and seek surgical evaluation if necessary.",
    
    "lactose intolerance": "Digestive discomfort after consuming dairy. Avoid dairy products or take lactase enzyme supplements.",
    
    "cough": "Persistent coughing may be due to infections, allergies, or acid reflux. Drink warm fluids, use cough drops, and rest.",
    
    "shortness of breath": "May be due to asthma, heart problems, or anxiety. Seek medical attention if severe or persistent.",
    
    "chronic obstructive pulmonary disease (COPD)": "A lung disease causing difficulty breathing. Avoid smoking, practice breathing exercises, and take prescribed medications.",
    
    "pneumothorax (collapsed lung)": "Sudden chest pain and difficulty breathing. Requires emergency medical treatment.",
    
    "palpitations": "Fast or irregular heartbeats. Avoid caffeine, manage stress, and consult a doctor if persistent.",
    
    "high cholesterol": "Increases risk of heart disease. Eat a healthy diet, exercise regularly, and consider medications if prescribed.",
    
    "varicose veins": "Enlarged veins, usually in the legs. Wear compression stockings, elevate legs, and avoid standing for long periods.",
    
    "deep vein thrombosis (DVT)": "Blood clot in the leg that can be dangerous. Stay active, avoid prolonged sitting, and seek medical treatment if symptoms arise.",
    
    "gallbladder pain": "Sharp pain in the upper right abdomen, often due to gallstones. Avoid fatty foods and seek medical evaluation if symptoms persist.",
    
    "kidney infection": "Causes back pain, fever, and frequent urination. Requires antibiotic treatment.",
    
    "bladder infection": "Frequent urination, burning sensation, and urgency. Stay hydrated and take prescribed antibiotics.",
    
    "prostate issues": "Common in older men, causing difficulty urinating. Maintain a healthy lifestyle and consult a doctor for treatment options.",
    
    "menopause symptoms": "Hot flashes, mood swings, and sleep disturbances. Hormone therapy and lifestyle changes may help manage symptoms.",
    
    "polycystic ovary syndrome (PCOS)": "Causes irregular periods, weight gain, and hormonal imbalances. Manage with a healthy diet, exercise, and medications.",
    
    "infertility": "Can be due to hormonal imbalances, lifestyle factors, or medical conditions. Seek medical evaluation and consider fertility treatments.",
    
    "erectile dysfunction": "Caused by stress, health conditions, or medications. Lifestyle changes, counseling, and medications can help.",
    
    "low testosterone": "Symptoms include fatigue, mood changes, and low libido. Exercise, maintain a healthy diet, and seek medical evaluation.",
    
    "osteoarthritis": "Degenerative joint disease causing pain and stiffness. Maintain a healthy weight, exercise, and use pain relievers.",
    
    "rheumatoid arthritis": "An autoimmune disorder causing joint inflammation. Medications and lifestyle changes help manage symptoms.",
    
    "multiple sclerosis (MS)": "Affects the nervous system, causing muscle weakness and coordination problems. Early diagnosis and medications can slow progression.",
    
    "Parkinson’s disease": "Affects movement and coordination. Medications and therapy help manage symptoms.",
    
    "Alzheimer’s disease": "Progressive memory loss and cognitive decline. Cognitive stimulation, medications, and support systems are important.",
    
    "stroke recovery": "Physical therapy, speech therapy, and lifestyle changes can help regain function after a stroke.",
    
    "mental health crisis": "Includes severe depression, anxiety, or suicidal thoughts. Seek professional help immediately.",
    
    "post-traumatic stress disorder (PTSD)": "Symptoms include flashbacks, anxiety, and sleep disturbances. Therapy and medications can help manage PTSD.",
    
    "seasonal affective disorder (SAD)": "Depression that occurs in colder months. Light therapy and vitamin D supplements may help.",
    
    "substance abuse": "Addiction to alcohol or drugs requires counseling, detox, and long-term support.",
    
    "sleep apnea": "Causes breathing pauses during sleep. Use a CPAP machine, maintain a healthy weight, and avoid alcohol before bed.",
    
    "snoring": "May be due to nasal congestion, obesity, or sleep apnea. Sleeping on your side and using nasal strips can help.",
    
    "burns": "Cool the burn with running water, avoid popping blisters, and apply aloe vera for relief.",
    
    "wound care": "Clean wounds with mild soap, apply antibiotic ointment, and cover with a sterile bandage.",
    "flu symptoms": "Common symptoms of flu include fever, cough, sore throat, runny or stuffy nose, body aches, headache, chills, and fatigue. Rest, hydration, and antiviral medications may help.",
    
    "back pain": "Back pain can be caused by muscle strain, poor posture, or underlying medical conditions. Apply heat or ice, practice good posture, and consider physical therapy for relief.",
    
    "headache": "Headaches can be triggered by stress, dehydration, or lack of sleep. Rest, hydrate, and take over-the-counter pain relievers if needed.",
    
    "migraine": "Migraines often involve throbbing head pain, nausea, and sensitivity to light and sound. Avoid triggers, use cold compresses, and take prescribed medications if necessary.",
    
    "pimple skin": "For pimples, maintain a gentle skincare routine, avoid squeezing, and use benzoyl peroxide or salicylic acid. A dermatologist can recommend stronger treatments if needed.",
    
    "sore throat": "A sore throat can result from infections or irritants. Gargle with warm salt water, stay hydrated, and use throat lozenges or honey for relief.",
    
    "ear pain": "Ear pain can be caused by infections, wax buildup, or pressure changes. Use warm compresses, avoid inserting objects into the ear, and see a doctor if severe.",
    
    "tooth pain": "Tooth pain may result from cavities, gum infections, or sensitivity. Rinse with salt water, avoid extremely hot or cold foods, and visit a dentist for evaluation.",
    
    "knee pain": "Knee pain can stem from injury, arthritis, or overuse. Rest, ice, compression, and elevation (RICE method) can help reduce discomfort.",
    
    "shoulder pain": "Shoulder pain may be due to muscle strain, rotator cuff injuries, or arthritis. Apply ice or heat, do gentle stretching, and consider physical therapy.",
    
    "chest pain": "Chest pain may have various causes, including muscle strain, heart problems, or acid reflux. Seek immediate medical help if pain is severe or accompanied by shortness of breath.",
    
    "abdominal pain": "Abdominal pain can be due to gas, indigestion, or infections. Avoid spicy foods, stay hydrated, and seek medical attention if pain is persistent.",
    
    "cold symptoms": "Common cold symptoms include a runny nose, sneezing, congestion, and sore throat. Rest, fluids, and over-the-counter medications can provide relief.",
    
    "skin rash": "Skin rashes can be caused by allergies, infections, or irritants. Use antihistamines, keep the skin moisturized, and avoid known triggers.",
    
    "itchy skin": "Itchy skin may be due to dryness, allergies, or insect bites. Moisturize frequently, use anti-itch creams, and avoid scratching.",
    
    "nausea": "Nausea can result from motion sickness, infections, or pregnancy. Sip ginger tea, eat small meals, and avoid strong odors to reduce symptoms.",
    
    "vomiting": "Vomiting can be due to food poisoning, infections, or other medical conditions. Stay hydrated and gradually introduce bland foods as tolerated.",
    
    "dizziness": "Dizziness may result from dehydration, low blood pressure, or inner ear problems. Sit or lie down, drink water, and avoid sudden movements.",
    
    "fatigue": "Fatigue can be caused by poor sleep, stress, or underlying health conditions. Prioritize rest, eat a balanced diet, and manage stress levels.",
    
    "constipation": "Constipation may be due to a low-fiber diet, dehydration, or inactivity. Increase fiber intake, drink plenty of water, and engage in regular physical activity.",
    
    "diarrhea": "Diarrhea can result from infections, food intolerances, or stress. Stay hydrated with electrolytes and eat bland foods like bananas and rice.",
    
    "heartburn": "Heartburn occurs due to acid reflux. Avoid spicy foods, eat smaller meals, and consider antacids for relief.",
    
    "joint pain": "Joint pain may be due to arthritis, overuse, or injury. Use ice packs, take anti-inflammatory medications, and stay active with low-impact exercises.",
    
    "swollen feet": "Swollen feet can result from fluid retention, standing too long, or circulation issues. Elevate the legs, wear compression socks, and stay hydrated.",
    
    "eye irritation": "Eye irritation may be due to allergies, dryness, or infections. Use lubricating eye drops, avoid rubbing the eyes, and wear protective eyewear outdoors.",
    
    "allergic reaction": "Symptoms include hives, swelling, and difficulty breathing. Take antihistamines and seek emergency care for severe reactions.",
    
    "depression": "Depression involves persistent sadness, loss of interest, and fatigue. Seek therapy, stay socially engaged, and consider medications if prescribed by a doctor.",
    
    "anxiety": "Anxiety can cause rapid heartbeat, restlessness, and excessive worry. Practice deep breathing, engage in relaxation techniques, and seek therapy if needed.",
    
    "insomnia": "Insomnia is difficulty falling or staying asleep. Establish a bedtime routine, limit screen time before bed, and avoid caffeine in the evening.",
    
    "sciatica": "Sciatica causes sharp pain along the sciatic nerve, often due to a herniated disc. Stretching, physical therapy, and pain relievers can help.",
    
    "tennis elbow": "Tennis elbow causes pain in the outer elbow due to overuse. Rest, ice, and wearing a brace can reduce symptoms.",
    
    "plantar fasciitis": "Heel pain from plantar fasciitis is common in the morning. Stretching, supportive shoes, and ice therapy can help.",
    
    "urinary tract infection (UTI)": "UTI symptoms include burning sensation during urination and frequent urge to urinate. Drink plenty of water and take antibiotics as prescribed.",
    
    "sinus infection": "Sinus infections cause congestion, facial pressure, and headaches. Use steam inhalation, nasal sprays, and stay hydrated.",
    
    "bronchitis": "Bronchitis causes a persistent cough and chest discomfort. Rest, drink fluids, and avoid smoking or pollutants.",
    
    "asthma": "Asthma leads to wheezing and shortness of breath. Use prescribed inhalers, avoid triggers, and practice breathing exercises.",
    
    "high blood pressure": "Hypertension can increase the risk of heart disease. Maintain a healthy diet, exercise regularly, and take medications as prescribed.",
    
    "diabetes": "Diabetes affects blood sugar levels. Manage with a balanced diet, regular exercise, and medication if needed.",
    
    "stroke symptoms": "Signs of stroke include sudden weakness, slurred speech, and vision loss. Seek emergency medical help immediately.",
    
    "heart attack symptoms": "Chest pain, shortness of breath, and arm pain may indicate a heart attack. Call emergency services immediately.",
    
    "liver disease": "Liver disease symptoms include jaundice, fatigue, and abdominal swelling. Avoid alcohol, eat a healthy diet, and seek medical evaluation.",
    
    "kidney stones": "Kidney stones cause severe lower back pain and difficulty urinating. Drink plenty of water and take pain relievers. Large stones may need medical removal.",
    
    "appendicitis": "Severe abdominal pain, especially on the lower right side, may indicate appendicitis. Seek immediate medical attention.",
    
    "pneumonia": "Pneumonia symptoms include cough, fever, and difficulty breathing. Antibiotics and rest are essential for recovery.",
    
    "thyroid disorder": "Thyroid problems can cause weight changes, fatigue, and mood swings. Regular check-ups and medication management are crucial.",
    
    "menstrual cramps": "Menstrual cramps can be relieved with heating pads, light exercise, and over-the-counter pain relievers.",
    
    "osteoporosis": "Osteoporosis weakens bones, increasing fracture risk. Ensure adequate calcium intake and engage in weight-bearing exercises.",
    
    "arthritis": "Arthritis causes joint pain and stiffness. Regular movement, anti-inflammatory medications, and a healthy diet can help manage symptoms.", 
    "fever": "Fever is a temporary increase in body temperature, often due to an illness. Rest, stay hydrated, and take fever-reducing medications like acetaminophen or ibuprofen.",
    "eye pain": "Eye pain can be caused by infections, dryness, or strain. Use lubricating eye drops, avoid prolonged screen time, and see a doctor if the pain persists or is severe.",
    "kidney pain": "Kidney pain can be caused by infections, stones, or other kidney-related issues. It's important to stay hydrated and seek medical attention for proper diagnosis and treatment.",
}